#Set up information about your PostgreSQL database.
database:
  host: "host"
  port: "port"
  name: "name"
  username: "username"
  password: "password"

#---------------------------------------------[              Messages              ]---------------------------------------------#
#If you want to select language, uncomment section "language" and enter a proper locale.
#If you want to add your own translation, open Bouncer.jar and modify one of messages.properties file or add your own translation
#named messages_lang.properties where "lang" is language name defined by ISO 639 standard.
#Built-in languages:
#en
#pl
#-------------------------------------------------------------------------------------------------------------------------------#

#language: en

argon2id:
  iterations: 4
  memory: 524_288

#Set up how plugin should work
settings:
  e-mail:
    authorization: true
    hint: true
  login_attempt:
    time: 60
    login_after_registration: true
    allow_book_reading: true
    blindness: true
    slowness: true
    moving_blockade: true
    sound:
      name: UI_BUTTON_CLICK
      increasing_volume: true
      max_volume: 100 #0-100
      pitch: 0
    title_text:
      display_time:
        fade_in: 30
        stay: 40
        fade_out: 30
        period: 120
    ip_blockade:
      blockade: true
      tries:
        same_ip:
          low: 25
          top: 30
        different_ip:
          low: 10
          top: 15
  session: true
  password_min_length: 5